// Full article bodies, keyed by slug. Only imported by the lazy-loaded
// BlogPostPage, so this never bloats the main bundle.
//
// Block types consumed by BlogPostPage.jsx:
//   { type: 'heading', level: 2|3, text }
//   { type: 'paragraph', text }
//   { type: 'list', ordered?: boolean, items: [] }
//   { type: 'step', number, instruction, screenshot: { id, alt }, tip? }
//   { type: 'callout', tone: 'privacy'|'tip'|'note', text }

const WHATSAPP_ANDROID_STEPS = [
  { instruction: 'Open the chat you want to analyse.', screenshot: { id: 'screenshot-whatsapp-android-step-1.png', alt: 'WhatsApp chat opened on an Android phone' } },
  { instruction: 'Tap the three dots ⋮ in the top-right corner.', screenshot: { id: 'screenshot-whatsapp-android-step-2.png', alt: 'Three-dot menu icon highlighted in WhatsApp on Android' } },
  { instruction: 'Tap More, then tap Export chat.', screenshot: { id: 'screenshot-whatsapp-android-step-3.png', alt: 'More menu showing the Export chat option' } },
  { instruction: 'Choose "Without media" — this keeps the file small and fast to upload.', screenshot: { id: 'screenshot-whatsapp-android-step-4.png', alt: 'Dialog asking whether to include media in the export' }, tip: 'Media makes the export file huge and ThirdPerson AI only needs the text.' },
  { instruction: 'Share or save the .txt file to yourself — email, Google Drive, or your Files app all work.', screenshot: { id: 'screenshot-whatsapp-android-step-5.png', alt: 'Android share sheet showing options to save the exported file' } },
  { instruction: 'Come back to ThirdPerson AI and upload that .txt file.', screenshot: { id: 'screenshot-whatsapp-android-step-6.png', alt: 'ThirdPerson AI upload screen with a .txt file selected' } },
];

const WHATSAPP_IPHONE_STEPS = [
  { instruction: 'Open the chat you want to analyse.', screenshot: { id: 'screenshot-whatsapp-iphone-step-1.png', alt: 'WhatsApp chat opened on an iPhone' } },
  { instruction: 'Tap the contact or group name at the top of the chat.', screenshot: { id: 'screenshot-whatsapp-iphone-step-2.png', alt: 'Contact name at the top of a WhatsApp chat on iPhone' } },
  { instruction: 'Scroll down and tap Export Chat.', screenshot: { id: 'screenshot-whatsapp-iphone-step-3.png', alt: 'Export Chat option in WhatsApp contact info screen' } },
  { instruction: 'Choose Without Media.', screenshot: { id: 'screenshot-whatsapp-iphone-step-4.png', alt: 'Prompt asking to attach media or export without media' } },
  { instruction: 'Tap Save to Files (or AirDrop it to yourself and save it from there).', screenshot: { id: 'screenshot-whatsapp-iphone-step-5.png', alt: 'iOS share sheet with Save to Files highlighted' } },
  { instruction: 'Open ThirdPerson AI and upload the saved .txt file.', screenshot: { id: 'screenshot-whatsapp-iphone-step-6.png', alt: 'ThirdPerson AI upload screen on iPhone' } },
];

export const BLOG_CONTENT = {
  'how-to-export-whatsapp-chats': [
    { type: 'paragraph', text: 'WhatsApp is the easiest app to export from, and it takes about a minute either way. Pick your device below.' },
    { type: 'callout', tone: 'privacy', text: 'Your chats are analysed securely and never shared.' },
    { type: 'heading', level: 2, text: 'Exporting on Android' },
    ...WHATSAPP_ANDROID_STEPS.map((step, index) => ({ type: 'step', number: index + 1, ...step })),
    { type: 'heading', level: 2, text: 'Exporting on iPhone' },
    ...WHATSAPP_IPHONE_STEPS.map((step, index) => ({ type: 'step', number: index + 1, ...step })),
    { type: 'heading', level: 3, text: 'What if I only want part of the conversation?' },
    { type: 'paragraph', text: 'WhatsApp always exports the full visible chat history on your device. If you only want a specific period, you can open the exported .txt file in any text editor and trim it before uploading, or simply paste the relevant section directly into ThirdPerson AI\'s paste box instead of uploading a file.' },
    { type: 'callout', tone: 'tip', text: 'Takes ~1 minute. Upload the .txt file directly — no need to convert or edit it.' },
  ],
  'how-to-export-instagram-messages': [
    { type: 'paragraph', text: 'Instagram doesn\'t let you export a single DM thread directly. Instead, you request your full data download, then pull out just the conversation you need. It sounds like more work than it is — here\'s the exact path.' },
    { type: 'callout', tone: 'note', text: 'Instagram can take anywhere from a few minutes to a few hours to prepare your file. You\'ll get a notification or email when it\'s ready.' },
    { type: 'step', number: 1, instruction: 'Open Instagram and go to Settings.', screenshot: { id: 'screenshot-instagram-step-1.png', alt: 'Instagram settings menu' } },
    { type: 'step', number: 2, instruction: 'Tap Accounts Centre.', screenshot: { id: 'screenshot-instagram-step-2.png', alt: 'Accounts Centre option in Instagram settings' } },
    { type: 'step', number: 3, instruction: 'Tap Your information and permissions.', screenshot: { id: 'screenshot-instagram-step-3.png', alt: 'Your information and permissions menu' } },
    { type: 'step', number: 4, instruction: 'Tap Download your information.', screenshot: { id: 'screenshot-instagram-step-4.png', alt: 'Download your information option' } },
    { type: 'step', number: 5, instruction: 'Select your account from the list.', screenshot: { id: 'screenshot-instagram-step-5.png', alt: 'Account selection screen' } },
    { type: 'step', number: 6, instruction: 'Choose "Some of your information" rather than everything — it\'s faster.', screenshot: { id: 'screenshot-instagram-step-6.png', alt: 'Choice between all information and some information' }, tip: 'Downloading everything can take much longer and gives you a lot you don\'t need.' },
    { type: 'step', number: 7, instruction: 'Select only Messages from the list of information types.', screenshot: { id: 'screenshot-instagram-step-7.png', alt: 'List of information types with Messages selected' } },
    { type: 'step', number: 8, instruction: 'Set the format to JSON and pick a date range that covers the conversation.', screenshot: { id: 'screenshot-instagram-step-8.png', alt: 'Format and date range selection screen' } },
    { type: 'step', number: 9, instruction: 'Submit the request and wait for Instagram\'s notification that it\'s ready.', screenshot: { id: 'screenshot-instagram-step-9.png', alt: 'Confirmation screen after submitting a data download request' } },
    { type: 'step', number: 10, instruction: 'Download the file, open the messages folder inside it, and upload the relevant conversation file to ThirdPerson AI.', screenshot: { id: 'screenshot-instagram-step-10.png', alt: 'Messages folder inside the downloaded Instagram data' } },
    { type: 'callout', tone: 'privacy', text: 'Your chats are analysed securely and never shared.' },
    { type: 'callout', tone: 'tip', text: 'Takes about 5 minutes to request, then a wait for Instagram. Upload the JSON file from the messages folder.' },
  ],
  'how-to-export-telegram-chat-history': [
    { type: 'callout', tone: 'note', text: 'Chat export is only available in Telegram Desktop. It is not available from the Telegram mobile app.' },
    { type: 'step', number: 1, instruction: 'Open Telegram Desktop on a computer. If you don\'t have it, it\'s a free download from telegram.org.', screenshot: { id: 'screenshot-telegram-step-1.png', alt: 'Telegram Desktop application window' } },
    { type: 'step', number: 2, instruction: 'Open the chat you want to analyse.', screenshot: { id: 'screenshot-telegram-step-2.png', alt: 'An open chat in Telegram Desktop' } },
    { type: 'step', number: 3, instruction: 'Click the three dots ⋮ at the top of the chat.', screenshot: { id: 'screenshot-telegram-step-3.png', alt: 'Three-dot menu at the top of a Telegram chat' } },
    { type: 'step', number: 4, instruction: 'Click Export chat history.', screenshot: { id: 'screenshot-telegram-step-4.png', alt: 'Export chat history option in the menu' } },
    { type: 'step', number: 5, instruction: 'Untick Photos, Videos, and other media types — you only need the text.', screenshot: { id: 'screenshot-telegram-step-5.png', alt: 'Export settings with media types unticked' }, tip: 'This keeps the file small and avoids uploading anything you don\'t need to.' },
    { type: 'step', number: 6, instruction: 'Choose JSON as the format. HTML also works if JSON isn\'t available in your version.', screenshot: { id: 'screenshot-telegram-step-6.png', alt: 'Format selection showing JSON and HTML options' } },
    { type: 'step', number: 7, instruction: 'Click Export and wait for Telegram to save the file to your computer.', screenshot: { id: 'screenshot-telegram-step-7.png', alt: 'Export progress indicator in Telegram Desktop' } },
    { type: 'step', number: 8, instruction: 'Upload the exported file to ThirdPerson AI.', screenshot: { id: 'screenshot-telegram-step-8.png', alt: 'ThirdPerson AI upload screen with a Telegram export selected' } },
    { type: 'callout', tone: 'privacy', text: 'Your chats are analysed securely and never shared.' },
    { type: 'callout', tone: 'tip', text: 'Takes about 2 minutes on a computer with Telegram Desktop installed.' },
  ],
  'how-to-export-imessage-chats': [
    { type: 'callout', tone: 'note', text: 'Apple does not provide an official way to export a full iMessage conversation as a file, so copy-paste is the most reliable option on a phone.' },
    { type: 'step', number: 1, instruction: 'Open the conversation in the Messages app.', screenshot: { id: 'screenshot-imessage-step-1.png', alt: 'An open iMessage conversation' } },
    { type: 'step', number: 2, instruction: 'Tap and hold on a message, then tap More to enter selection mode.', screenshot: { id: 'screenshot-imessage-step-2.png', alt: 'Message selection mode in Messages app' } },
    { type: 'step', number: 3, instruction: 'Tap each message you want to include, then tap the share icon to copy them.', screenshot: { id: 'screenshot-imessage-step-3.png', alt: 'Multiple messages selected with the share icon visible' } },
    { type: 'step', number: 4, instruction: 'Open ThirdPerson AI and paste the copied text directly into the paste box instead of uploading a file.', screenshot: { id: 'screenshot-imessage-step-4.png', alt: 'ThirdPerson AI paste box with iMessage text pasted in' } },
    { type: 'step', number: 5, instruction: 'For a longer conversation, repeat this for each section and paste them in chronological order.', tip: 'Keeping the order intact matters more than getting every single message — a representative stretch of the conversation is enough.' },
    { type: 'paragraph', text: 'If you use a Mac, the Messages app there allows you to select and copy a longer stretch of conversation at once, which can be faster than doing it message-by-message on a phone.' },
    { type: 'callout', tone: 'privacy', text: 'Your chats are analysed securely and never shared.' },
    { type: 'callout', tone: 'tip', text: 'Takes about 2 minutes. Paste the text — there is no file to upload for this method.' },
  ],
  'how-to-export-messenger-chats': [
    { type: 'callout', tone: 'note', text: 'Messenger is part of the same Meta data-download tool as Instagram, so if you\'ve exported an Instagram chat before, this will feel familiar.' },
    { type: 'step', number: 1, instruction: 'Go to your Facebook or Messenger Accounts Centre information export settings.', screenshot: { id: 'screenshot-messenger-step-1.png', alt: 'Accounts Centre settings menu' } },
    { type: 'step', number: 2, instruction: 'Request a copy or export of your information.', screenshot: { id: 'screenshot-messenger-step-2.png', alt: 'Download your information option' } },
    { type: 'step', number: 3, instruction: 'Select Messages from the list of information types.', screenshot: { id: 'screenshot-messenger-step-3.png', alt: 'Information type list with Messages selected' } },
    { type: 'step', number: 4, instruction: 'Choose your date range and set the format to JSON.', screenshot: { id: 'screenshot-messenger-step-4.png', alt: 'Date range and format selection screen' } },
    { type: 'step', number: 5, instruction: 'Submit the request and download the file once Meta notifies you it\'s ready.', screenshot: { id: 'screenshot-messenger-step-5.png', alt: 'Confirmation screen after submitting the export request' } },
    { type: 'step', number: 6, instruction: 'Open the downloaded file and upload the relevant conversation to ThirdPerson AI.', screenshot: { id: 'screenshot-messenger-step-6.png', alt: 'ThirdPerson AI upload screen with a Messenger export selected' } },
    { type: 'callout', tone: 'privacy', text: 'Your chats are analysed securely and never shared.' },
    { type: 'callout', tone: 'tip', text: 'Takes about 5 minutes to request, then a short wait for Meta to prepare it.' },
  ],
  'how-to-export-snapchat-chats': [
    { type: 'callout', tone: 'note', text: 'Snapchat may not include messages that already disappeared or were never saved by either person — it can only export what Snapchat still has a record of.' },
    { type: 'step', number: 1, instruction: 'Open Snapchat and go to Settings, then My Data.', screenshot: { id: 'screenshot-snapchat-step-1.png', alt: 'Snapchat My Data settings screen' } },
    { type: 'step', number: 2, instruction: 'Request your data.', screenshot: { id: 'screenshot-snapchat-step-2.png', alt: 'Request my data button' } },
    { type: 'step', number: 3, instruction: 'If given the option, select chat or message history specifically.', screenshot: { id: 'screenshot-snapchat-step-3.png', alt: 'Data type selection with chat history highlighted' } },
    { type: 'step', number: 4, instruction: 'Submit the request and wait for Snapchat to prepare your file — you\'ll get a notification.', screenshot: { id: 'screenshot-snapchat-step-4.png', alt: 'Confirmation screen after requesting Snapchat data' } },
    { type: 'step', number: 5, instruction: 'Download the prepared file and upload the relevant part to ThirdPerson AI.', screenshot: { id: 'screenshot-snapchat-step-5.png', alt: 'ThirdPerson AI upload screen with a Snapchat data file selected' } },
    { type: 'callout', tone: 'privacy', text: 'Your chats are analysed securely and never shared.' },
    { type: 'callout', tone: 'tip', text: 'Takes about 5 minutes to request, then a short wait for Snapchat to prepare it.' },
  ],
  'the-science-of-marriage-success': [
    { type: 'paragraph', text: 'In the 1990s, psychologist John Gottman set up what he called a "Love Lab" at the University of Washington. Couples would spend time in an apartment-like observation suite while researchers tracked their conversations, heart rates, and facial expressions down to the smallest muscle twitch. The goal was simple: figure out what actually separates couples who stay together from couples who don\'t.' },
    { type: 'paragraph', text: 'The results were so consistent that Gottman could predict, with over 90% accuracy in some studies, which couples would divorce within a few years — just by watching how they argued for a few minutes. Not what they argued about. How.' },
    { type: 'heading', level: 2, text: 'The 5:1 ratio' },
    { type: 'paragraph', text: 'One of Gottman\'s most-cited findings is what\'s often called the "magic ratio": stable, happy couples maintain roughly five positive interactions for every one negative interaction during conflict. This doesn\'t mean five compliments for every criticism in daily life — it specifically applies to how couples behave while actually disagreeing.' },
    { type: 'paragraph', text: 'A positive interaction can be small: a moment of humour in the middle of tension, a validating "I get why you\'re upset," physical affection, or genuine curiosity about the other person\'s point of view. Couples heading toward divorce, by contrast, tend to drop toward a 1:1 ratio or worse — every criticism is met with an equal or greater negative response, with no positivity to buffer it.' },
    { type: 'callout', tone: 'note', text: 'The ratio matters more during conflict than during calm moments — it is specifically about how a couple handles disagreement, not how often they say nice things in general.' },
    { type: 'heading', level: 2, text: 'The Four Horsemen' },
    { type: 'paragraph', text: 'Gottman named four communication patterns "the Four Horsemen of the Apocalypse" because of how reliably they predict relationship breakdown when they become habitual.' },
    { type: 'list', items: [
      'Criticism — attacking someone\'s character rather than addressing a specific behaviour ("You never think about anyone but yourself" instead of "I felt hurt that you forgot to call").',
      'Contempt — mockery, sarcasm, eye-rolling, or name-calling that communicates disgust or superiority. Gottman found this to be the single strongest predictor of divorce.',
      'Defensiveness — responding to a concern with self-protection and counter-blame instead of hearing it ("Well, you do it too" instead of acknowledging the point).',
      'Stonewalling — shutting down and withdrawing from the conversation entirely, often as a response to feeling physiologically overwhelmed.',
    ] },
    { type: 'paragraph', text: 'These four rarely appear alone — they tend to escalate in sequence. Criticism invites defensiveness, defensiveness invites contempt, and contempt eventually pushes one partner into stonewalling just to cope with the intensity.' },
    { type: 'heading', level: 2, text: 'What this has to do with your text messages' },
    { type: 'paragraph', text: 'Gottman\'s research was built on in-person conversation, but the same underlying patterns show up in text — often more visibly, because text leaves a written record. A pattern of one-word replies after a disagreement can be a form of stonewalling. A message like "must be nice to only think about yourself" is textbook criticism. Sarcastic replies with no warmth underneath are contempt in text form.' },
    { type: 'paragraph', text: 'This is exactly the kind of pattern ThirdPerson AI is built to surface. A single message rarely tells you much. But looking across weeks or months of a real conversation — how often repair attempts happen after conflict, how balanced the effort is, whether warmth returns after tension — starts to resemble the same signal Gottman spent decades studying in person, just visible in the chat history you already have.' },
    { type: 'heading', level: 2, text: 'What actually helps' },
    { type: 'paragraph', text: 'Gottman\'s more hopeful finding is that the Four Horsemen aren\'t fatal on their own — what matters is whether a couple has "repair attempts" that work. A repair attempt is any effort to de-escalate: a joke, an apology, a hand reaching out, a simple "can we start over?" Couples who stay together aren\'t the ones who never fight. They\'re the ones whose repair attempts land, and who keep making them.' },
    { type: 'callout', tone: 'tip', text: 'If you want to see these patterns in your own conversations, upload a chat to ThirdPerson AI — the report looks specifically for effort balance, repair patterns, and recurring conflict signals.' },
  ],
  'texting-habits-relationship-health': [
    { type: 'paragraph', text: 'Nobody\'s relationship is judged fairly by a single text message taken out of context. But patterns, repeated over weeks and months, tell a much more honest story than any one conversation can. Here are ten habits worth noticing in your own chat history.' },
    { type: 'heading', level: 2, text: '1. Who initiates, and how often' },
    { type: 'paragraph', text: 'If one person is almost always the one to say "hey" first, it\'s worth asking why. Occasional imbalance is normal — consistent one-sided initiation over months is a pattern worth naming.' },
    { type: 'heading', level: 2, text: '2. Response time under normal circumstances' },
    { type: 'paragraph', text: 'Busy people are still busy people, and slow replies aren\'t automatically a red flag. But a consistent, growing gap in response time — especially after it used to be quick — often reflects a shift in priority or interest before either person says it out loud.' },
    { type: 'heading', level: 2, text: '3. How repair happens after a disagreement' },
    { type: 'paragraph', text: 'Every relationship has friction. The healthier pattern isn\'t the absence of conflict — it\'s what happens in the hour or day afterward. Does someone reach out first? Is there a joke that breaks the tension? Or does the silence just stretch until it\'s quietly forgotten (and quietly unresolved)?' },
    { type: 'heading', level: 2, text: '4. Effort balance in the little things' },
    { type: 'paragraph', text: 'Who remembers to ask "how did that thing go?" the next day? Who follows up on the small details the other person mentioned in passing? This kind of effort is easy to miss in the moment but adds up clearly over a long chat history.' },
    { type: 'heading', level: 2, text: '5. One-word replies during otherwise normal conversation' },
    { type: 'paragraph', text: 'Context matters — a one-word reply during a busy day is nothing. A pattern of one-word replies specifically after certain topics come up (commitment, plans, feelings) is a more specific signal.' },
    { type: 'heading', level: 2, text: '6. How mixed signals get handled' },
    { type: 'paragraph', text: 'Healthy communication tends to name confusion directly ("I wasn\'t sure what you meant by that") rather than letting it sit and fester into assumption.' },
    { type: 'heading', level: 2, text: '7. Humour that lands vs. humour that doesn\'t' },
    { type: 'paragraph', text: 'Shared humour is one of the strongest glue points in any relationship. Sarcasm that consistently has an edge to it — the kind that gets a "lol" but not an actual laugh — is a different thing entirely, and worth telling apart from playful teasing.' },
    { type: 'heading', level: 2, text: '8. Whether apologies actually happen' },
    { type: 'paragraph', text: 'Not every disagreement needs a formal apology, but a pattern where one person never acknowledges being in the wrong — even lightly — tends to leave the other person carrying more than their share.' },
    { type: 'heading', level: 2, text: '9. Emoji and affection language over time' },
    { type: 'paragraph', text: 'A gradual drop in warmth markers — emoji, pet names, "good morning" texts — isn\'t proof of anything by itself, but it\'s a genuinely useful trendline to notice rather than dismiss.' },
    { type: 'heading', level: 2, text: '10. Consistency between words and plans' },
    { type: 'paragraph', text: 'Does "we should hang out soon" turn into an actual plan, or does it stay a nice sentence that never becomes a date on the calendar? Intentions are easy to text. Follow-through is the pattern that actually matters.' },
    { type: 'callout', tone: 'tip', text: 'These patterns are much easier to see across months of messages than in your memory of a few conversations — which is exactly what a chat analysis is built to surface.' },
  ],
  'why-we-fight-over-text': [
    { type: 'paragraph', text: 'A message that would sound perfectly neutral out loud can read as cold, sarcastic, or angry in text. This isn\'t a flaw in how you communicate — it\'s a predictable gap in how text works as a medium, and understanding it can defuse a surprising number of arguments before they start.' },
    { type: 'heading', level: 2, text: 'Text removes almost everything except the words' },
    { type: 'paragraph', text: 'In person, meaning comes from tone of voice, facial expression, timing, and body language as much as from the actual words used. Researchers estimate that a large share of emotional meaning in face-to-face communication comes from these non-verbal channels. Text strips nearly all of it away, leaving just the words — and words alone are a surprisingly ambiguous way to convey emotion.' },
    { type: 'paragraph', text: '"Sure, whatever works" can be relaxed agreement or quiet resentment, and the words on the screen look identical either way.' },
    { type: 'heading', level: 2, text: 'Your brain fills the gap with whatever you already expect' },
    { type: 'paragraph', text: 'When information is ambiguous, people don\'t sit in uncertainty — they fill in the missing tone with whatever their brain already predicts. If you\'re already anxious about where a relationship stands, a short reply reads as distance. If you already feel criticised, a neutral comment reads as another dig. This is sometimes called negative sentiment override: once a relationship enters a slightly negative frame, ambiguous messages get interpreted negatively by default, which then reinforces the negative frame — a feedback loop that\'s easy to fall into and hard to notice from inside it.' },
    { type: 'heading', level: 2, text: 'Timing carries meaning that was never intended' },
    { type: 'paragraph', text: 'A reply that comes twelve hours later might mean someone was in back-to-back meetings, asleep, or genuinely didn\'t know what to say. But the person waiting rarely experiences it that way in the moment — the gap itself becomes information, whether or not it was meant to be.' },
    { type: 'heading', level: 2, text: 'Punctuation and length do a lot of uninvited work' },
    { type: 'paragraph', text: 'A period at the end of a short text can read as clipped or annoyed, even when it\'s just habitual grammar. A long, detailed message can read as caring or as over-explaining, depending entirely on the mood of the person reading it. None of this is really about grammar — it\'s about the reader\'s state of mind doing the interpreting.' },
    { type: 'heading', level: 2, text: 'What actually helps' },
    { type: 'list', items: [
      'Naming the ambiguity out loud ("that came across a bit flat to me, is everything okay?") instead of assuming the worst reading and reacting to it.',
      'Moving genuinely important or emotionally loaded conversations to a call rather than resolving them entirely over text.',
      'Noticing your own state before reading a message — if you\'re already stressed or anxious, that\'s worth accounting for before deciding what a message "really means".',
      'Looking at the pattern over time rather than any single message — one flat reply means very little; a consistent pattern of them means more.',
    ] },
    { type: 'paragraph', text: 'This last point is where a proper chat analysis becomes genuinely useful. A single confusing message is nearly impossible to interpret fairly on its own. A pattern across weeks or months — response time trends, recurring flags, how conflict actually gets repaired — tells a much more honest story than any one text ever could.' },
    { type: 'callout', tone: 'tip', text: 'If a conversation keeps leaving you unsure what someone actually meant, a full chat analysis often makes the pattern much clearer than re-reading the same messages again.' },
  ],
};

export function getBlogContentBySlug(slug) {
  return BLOG_CONTENT[slug] || null;
}
