const PRIVACY_NOTE = 'Your chats are analysed securely and never shared.';

export const EXPORT_GUIDES = {
  WhatsApp: {
    estimatedTime: '~1 minute',
    fileFormat: 'A .txt file — this is what WhatsApp creates automatically when you export.',
    privacyNote: PRIVACY_NOTE,
    blogSlug: 'how-to-export-whatsapp-chats',
    variants: [
      {
        os: 'Android',
        steps: [
          'Open the chat you want to analyse.',
          'Tap the three dots ⋮ in the top-right corner.',
          'Tap More.',
          'Tap Export chat.',
          'Choose "Without media" — this makes the file smaller and faster to upload.',
          'Save or share the exported .txt file to yourself (e.g. via email, Drive, or Files).',
          'Upload that .txt file here.',
        ],
      },
      {
        os: 'iPhone',
        steps: [
          'Open the chat you want to analyse.',
          'Tap the contact or group name at the top of the chat.',
          'Scroll down and tap Export Chat.',
          'Choose Without Media.',
          'Tap Save to Files (or AirDrop it to yourself, then save it).',
          'Upload that .txt file here.',
        ],
      },
    ],
  },
  iMessage: {
    estimatedTime: '~2 minutes',
    fileFormat: 'Pasted text works best — iPhone does not offer a built-in bulk export for iMessage.',
    privacyNote: PRIVACY_NOTE,
    blogSlug: 'how-to-export-imessage-chats',
    note: 'Apple does not provide an official way to export a full iMessage conversation as a file, so copy-paste is the most reliable option.',
    steps: [
      'Open the conversation in the Messages app.',
      'Tap and hold on a message, then tap More to enter selection mode.',
      'Select the messages you want to include, then tap the share icon to copy them.',
      'Paste the copied text directly into the paste box here instead of uploading a file.',
      'For a longer history, repeat this for each section of the conversation and paste them in order.',
    ],
  },
  Telegram: {
    estimatedTime: '~2 minutes',
    fileFormat: 'A JSON file is the most reliable, but HTML also works.',
    privacyNote: PRIVACY_NOTE,
    blogSlug: 'how-to-export-telegram-chat-history',
    note: 'Chat export is only available in Telegram Desktop — it is not available from the mobile app.',
    steps: [
      'Open Telegram Desktop on a computer (download it free if you do not have it).',
      'Open the chat you want to analyse.',
      'Click the three dots ⋮ at the top of the chat.',
      'Click Export chat history.',
      'Untick Photos, Videos, and other media — you only need the text.',
      'Choose JSON as the format (HTML also works if JSON is not available).',
      'Click Export and wait for the file to save.',
      'Upload the exported file here.',
    ],
  },
  Instagram: {
    estimatedTime: '~5 minutes to request, then a short wait for Instagram to prepare it',
    fileFormat: 'A JSON file, found inside the "messages" folder of your downloaded data.',
    privacyNote: PRIVACY_NOTE,
    blogSlug: 'how-to-export-instagram-messages',
    note: 'Instagram can take anywhere from a few minutes to a few hours to prepare your file — you will get a notification when it is ready to download.',
    steps: [
      'Open Instagram and go to Settings.',
      'Tap Accounts Centre.',
      'Tap Your information and permissions.',
      'Tap Download your information.',
      'Select your account.',
      'Choose "Some of your information".',
      'Select only Messages from the list.',
      'Set the format to JSON and choose a date range.',
      'Submit the request and wait for Instagram to email or notify you when it is ready.',
      'Download the file, open the messages folder, and upload the relevant conversation file here.',
    ],
  },
  Messenger: {
    estimatedTime: '~5 minutes to request, then a short wait',
    fileFormat: 'A JSON file, found inside the downloaded data package.',
    privacyNote: PRIVACY_NOTE,
    blogSlug: 'how-to-export-messenger-chats',
    note: 'Messenger is part of the same Meta data-download tool as Instagram, so the steps are very similar.',
    steps: [
      'Go to your Facebook/Messenger Accounts Centre information export settings.',
      'Request a copy or export of your information.',
      'Select Messages from the list of information types.',
      'Choose your date range and set the format to JSON.',
      'Submit the request and download the file when it is ready.',
      'Upload the relevant message file here.',
    ],
  },
  Snapchat: {
    estimatedTime: '~5 minutes to request, then a short wait',
    fileFormat: 'The chat/message data file included in your download.',
    privacyNote: PRIVACY_NOTE,
    blogSlug: 'how-to-export-snapchat-chats',
    note: 'Snapchat may not include messages that already disappeared or were never saved by either person.',
    steps: [
      'Open Snapchat and go to Settings > My Data.',
      'Request your data.',
      'Select the chat or message history option, if available.',
      'Submit the request and wait for Snapchat to prepare your file.',
      'Download the prepared file.',
      'Upload the relevant file here.',
    ],
  },
  Other: {
    estimatedTime: '~1-2 minutes',
    fileFormat: '.txt, .json, or .csv — or simply paste the conversation as text.',
    privacyNote: PRIVACY_NOTE,
    steps: [
      'Check your messaging app\'s settings for a "Download my data" or "Export chat" option.',
      'Export as .txt, .json, or .csv if your app supports it.',
      'If there is no export option, copy and paste the conversation text directly instead.',
      'Remove attachments and any details you would prefer to keep private before uploading.',
      'Upload the file, or paste the text, here.',
    ],
  },
};
