import ParticleBackground from '../components/ParticleBackground.jsx';

const updated = new Intl.DateTimeFormat('en-IN', { dateStyle: 'long' }).format(new Date());

const termsSections = [
  ['Who this agreement is with', 'These Terms govern your use of ThirdPerson AI ("we", "us"). By creating an account or using the app, you agree to these Terms and to the Privacy Policy.'],
  ['What ThirdPerson AI is', 'ThirdPerson AI analyses conversation text you provide and generates reflective, interpretive insights: sentiment and communication patterns, personality-style summaries, compatibility signals, and an AI chat companion ("Relationship Guide") for follow-up questions. Outputs are probabilistic reflections, not diagnoses, professional advice, or proof of anyone\'s intentions.'],
  ['Eligibility', 'You must be at least 16 years old to use ThirdPerson AI. By using the app you confirm you meet this requirement.'],
  ['Your responsibility for uploaded content', 'You are solely responsible for the conversations you upload or paste, including having a reasonable basis to analyse messages from people who are not ThirdPerson AI users. Do not upload content you do not have the right to share.'],
  ['Prohibited use', 'You must not use ThirdPerson AI to stalk, harass, manipulate, surveil, coerce, blackmail, threaten, or make final judgments used to harm another person. We may suspend or terminate accounts used in this way.'],
  ['Free tier and paid credits', 'A limited number of free analyses are available per account. Additional Relationship Reports and Guide Chats are sold as pay-as-you-go credit packs. Credits are tied to your account, do not expire on a rolling basis once granted, and are not transferable between accounts.'],
  ['Payments', 'Paid credit packs are billed in Indian Rupees (INR) through our payment processor. You agree to provide accurate billing information. See our Refund & Cancellation Policy for how top-ups are handled.'],
  ['No professional advice', 'ThirdPerson AI is not therapy, counselling, legal advice, or a substitute for professional judgment. If you are in crisis or experiencing abuse, please contact a licensed professional or local emergency services.'],
  ['AI limitations', 'Outputs are generated by automated systems and can be incomplete, wrong, or miss context that is not visible in the uploaded text. Do not treat any output as certain or final.'],
  ['Account suspension', 'We may suspend or terminate access for violation of these Terms, suspected abuse of the credit system, or activity that risks the security of the service or other users.'],
  ['Intellectual property', 'You retain rights to the conversation content you upload. We retain rights to the ThirdPerson AI product, branding, and the structure of generated reports.'],
  ['Disclaimers and limitation of liability', 'The service is provided "as is" without warranties of any kind. To the extent permitted by law, ThirdPerson AI is not liable for indirect, incidental, or consequential damages arising from use of the app or reliance on its outputs.'],
  ['Changes to these Terms', 'We may update these Terms as the product evolves. Material changes will be reflected on this page with an updated date.'],
  ['Governing law', 'These Terms are governed by the laws of India, without regard to conflict-of-law principles.'],
  ['Contact', 'Questions about these Terms can be sent to legal@thethirdperson.ai.'],
];

export default function TermsPage() {
  return (
    <section className="relative min-h-screen overflow-hidden px-4 pb-16 pt-28 sm:px-8">
      <ParticleBackground className="opacity-45" />
      <div className="relative mx-auto max-w-[1320px]">
        <div className="corner-frame accent-panel p-6 sm:p-12">
          <p className="tech-label text-smoke">Terms of Service</p>
          <h1 className="serif-title mt-5 max-w-4xl text-5xl leading-tight sm:text-7xl">The agreement behind ThirdPerson AI.</h1>
          <p className="mt-3 font-mono text-xs uppercase tracking-[0.14em] text-purple-200/80">Last updated: {updated}</p>
          <p className="mt-6 max-w-3xl text-sm leading-8 text-smoke">
            These Terms explain what you can expect from ThirdPerson AI, what we expect from you, and how paid credits, refunds, and account use work.
          </p>
        </div>

        <div className="mt-8 grid gap-8 lg:grid-cols-[280px_1fr]">
          <aside className="hidden h-fit border border-purple-300/15 bg-black/45 p-5 lg:sticky lg:top-28 lg:block">
            <p className="tech-label mb-4 text-smoke">Sections</p>
            <div className="space-y-2">
              {termsSections.map(([title], index) => (
                <a key={title} href={`#terms-${index}`} className="block text-sm leading-6 text-ash transition hover:text-bone">
                  {String(index + 1).padStart(2, '0')} {title}
                </a>
              ))}
            </div>
          </aside>
          <div className="space-y-5">
            {termsSections.map(([title, body], index) => (
              <section id={`terms-${index}`} key={title} className="thin-panel scroll-mt-28 p-6">
                <p className="tech-label text-purple-200">{String(index + 1).padStart(2, '0')}</p>
                <h2 className="serif-title mt-3 text-3xl">{title}</h2>
                <p className="mt-4 text-sm leading-8 text-smoke">{body}</p>
              </section>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
